### ISSUE TITLE
Missing release tag

### ISSUE THREAD

**Issue by estshy** [Kuzirashi/ember-link-action#9]
I am trying to fix all deprecation notes and one comes from ember-link-action as I am using the latest release (0.0.34). Why there is no release tag for the version that we can fetch from master? I don't want to depend on master branch as it will most probably change in future, also adding hash commit in package.json sucks. We definitely need 0.0.35 release.

**Comment by Kuzirashi** [comment]
Hey, thanks @estshy and fellow likers for bringing my attention to this! :)

There's new release - v0.0.35! :)

I've also added unit tests, made Mixin more SOLID, fixed tests on CI, upgraded CLI to v2.8.0-beta.2.

Please leave a star :star2: for this repository if you enjoy my work. :) If you have any feedback, ideas on this addon, or creating new Ember addons, because you feel there's space to improve something please write **kuzirashi@interia.pl**.

I'm also open to all pull requests. :)
